<?php

namespace Database\Seeders;

use App\Models\Account;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChartOfAccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('accounts')->insert([
            // [
            //     'account_code' => 6000,
            //     'account_name' => 'Productive Labour',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6001,
            //     'account_name' => 'Cost of Sales Labour',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6002,
            //     'account_name' => 'Sub-Contractors',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6100,
            //     'account_name' => 'Sales Commissions',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6200,
            //     'account_name' => 'Sales Promotions',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6202,
            //     'account_name' => 'Gifts and Samples',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6203,
            //     'account_name' => 'Brochures and Banners',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6900,
            //     'account_name' => 'Miscellaneous Expenses',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 6901,
            //     'account_name' => 'General Discounts allowed',
            //     'account_type' => 'Direct Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7000,
            //     'account_name' => 'Gross Wages',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7001,
            //     'account_name' => 'Directors Salaries',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7002,
            //     'account_name' => 'Directors Remuneration',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7004,
            //     'account_name' => 'Wages - Regular',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7005,
            //     'account_name' => 'Wages - Casual',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7006,
            //     'account_name' => 'Salary and Wage Taxes',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7007,
            //     'account_name' => 'Gratuity Expense',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7008,
            //     'account_name' => 'Recruitment Expenses',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7009,
            //     'account_name' => 'Adjustments',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7100,
            //     'account_name' => 'Office or House Rent',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7102,
            //     'account_name' => 'Water Charges',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7104,
            //     'account_name' => 'Premises Insurance',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7201,
            //     'account_name' => 'Gas Charges',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7203,
            //     'account_name' => 'Gas Charges',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7300,
            //     'account_name' => 'Fuel Charges',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7301,
            //     'account_name' => 'Repairs and Servicing',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7302,
            //     'account_name' => 'Licences',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7303,
            //     'account_name' => 'Vehicle Insurance',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7304,
            //     'account_name' => 'Miscellaneous Motor Expenses',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7400,
            //     'account_name' => 'Travelling costs',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7401,
            //     'account_name' => 'Car Rent costs',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7402,
            //     'account_name' => 'Travel Hotel costs',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7502,
            //     'account_name' => 'Telephone Costs',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7503,
            //     'account_name' => 'Internet Costs',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ],
            // [
            //     'account_code' => 7504,
            //     'account_name' => 'Office Stationery',
            //     'account_type' => 'Other Expenses',
            //     'dr_cr' => 'dr',
            //     'opening_date' => now(),
            //     'locked' => 1,
            // ]

            // Fixed asset
            [
                'account_code' => 12,
                'account_name' => 'Owned Land',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 13,
                'account_name' => 'Long Term Rented Land',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 20,
                'account_name' => 'Equipment',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 21,
                'account_name' => 'Equipment Depreciation',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 31,
                'account_name' => 'Office Equipment Depreciation',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 40,
                'account_name' => 'Furniture and Fixtures',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 41,
                'account_name' => 'Furniture/Fixture Depreciation',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 50,
                'account_name' => 'Motor Vehicles',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 51,
                'account_name' => 'Motor Vehicles Depreciation',
                'account_type' => 'Fixed Asset',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            // current asset
            [
                'account_code' => 1002,
                'account_name' => 'Manufacturing Process Products',
                'account_type' => 'Other Current Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 1003,
                'account_name' => 'Manufactured Ready-to-Sell Products',
                'account_type' => 'Other Current Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 1220,
                'account_name' => 'Building Society Account',
                'account_type' => 'Other Current Asset',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            // current liability
            [
                'account_code' => 2202,
                'account_name' => 'VAT Payable',
                'account_type' => 'Current Liability',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 2210,
                'account_name' => 'Payroll Taxes Payable',
                'account_type' => 'Current Liability',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 2250,
                'account_name' => 'Unearned Revenue',
                'account_type' => 'Current Liability',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            // equity
            [
                'account_code' => 3000,
                'account_name' => 'Common Shares',
                'account_type' => 'Equity',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 3010,
                'account_name' => 'Preferred Shares',
                'account_type' => 'Equity',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 3011,
                'account_name' => 'Additional Paid-in Capital',
                'account_type' => 'Equity',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 3101,
                'account_name' => 'Retained Earnings',
                'account_type' => 'Equity',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 3300,
                'account_name' => 'Dividends Declared (Not yet paid)',
                'account_type' => 'Equity',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 3301,
                'account_name' => 'Dividends Paid',
                'account_type' => 'Equity',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            // sales and income
            [
                'account_code' => 4200,
                'account_name' => 'Sales Of Assets',
                'account_type' => 'Sales',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 4902,
                'account_name' => 'Commissions Received Income',
                'account_type' => 'Other Income',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            // Cost of sale
            [
                'account_code' => 5003,
                'account_name' => 'Packaging Expenses',
                'account_type' => 'Cost Of Sale',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],

            [
                'account_code' => 5100,
                'account_name' => 'Shipping Costs',
                'account_type' => 'Cost Of Sale',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],

            [
                'account_code' => 5101,
                'account_name' => 'Import Taxes',
                'account_type' => 'Cost Of Sale',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],

            [
                'account_code' => 5102,
                'account_name' => 'Goods Transportation',
                'account_type' => 'Cost Of Sale',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],

            [
                'account_code' => 5200,
                'account_name' => 'Initial Inventory',
                'account_type' => 'Cost Of Sale',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],

            [
                'account_code' => 5201,
                'account_name' => 'Closing Stock',
                'account_type' => 'Cost Of Sale',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 5202,
                'account_name' => 'Purchase Discount Allowed',
                'account_type' => 'Cost Of Sale',
                'dr_cr' => 'cr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            // Direct expenses
            [
                'account_code' => 6000,
                'account_name' => 'Productive Labour',
                'account_type' => 'Direct Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 6001,
                'account_name' => 'Cost of Sales Labour',
                'account_type' => 'Direct Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            // Other expenses 2
            [
                'account_code' => 7600,
                'account_name' => 'Legal Fees',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7601,
                'account_name' => 'Audit and Accountancy Fees',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7602,
                'account_name' => 'Consultancy Fees',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7603,
                'account_name' => 'Professional Fees',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7700,
                'account_name' => 'Equipment Rent',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7701,
                'account_name' => 'Office Machine Maintenance',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7800,
                'account_name' => 'Repairs and Renewals',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7801,
                'account_name' => 'Cleaning Costs',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7802,
                'account_name' => 'Laundry Costs',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7803,
                'account_name' => 'Premises Expenses',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7900,
                'account_name' => 'Bank Charges',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7901,
                'account_name' => 'Currency Charges',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7902,
                'account_name' => 'Credit & Loan charges',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 7905,
                'account_name' => 'Depreciation',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8000,
                'account_name' => 'Plant/Machinery Depreciation',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8001,
                'account_name' => 'Furniture/Fitting Depreciation',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8002,
                'account_name' => 'Vehicle Depreciation',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8003,
                'account_name' => 'Office Equipment Depreciation',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8100,
                'account_name' => 'Bad Debt Write Off',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8102,
                'account_name' => 'Bad Debt Provision',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8200,
                'account_name' => 'Donations',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8201,
                'account_name' => 'Subscriptions',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8202,
                'account_name' => 'Clothing Costs',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8203,
                'account_name' => 'Training Costs',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8204,
                'account_name' => 'Insurance',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
            [
                'account_code' => 8205,
                'account_name' => 'Refreshments',
                'account_type' => 'Other Expenses',
                'dr_cr' => 'dr',
                'opening_date' => now(),
                'locked' => 1,
            ],
        ]);
    }
}