<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    protected $userId;
    protected $businessId;

    public function __construct($userId, $businessId)
    {
        $this->userId     = $userId;
        $this->businessId = $businessId;
    }

    public function run()
    {
        DB::table('currency')->insert([
            [
                'name'          => 'AED',
                'exchange_rate' => 3.672504,
                'base_currency' => 0,
                'description'   => 'United Arab Emirates Dirham - AED (د.إ)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'AFN',
                'exchange_rate' => 87.000368,
                'base_currency' => 0,
                'description'   => 'Afghan Afghani - AFN (؋)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ALL',
                'exchange_rate' => 101.280403,
                'base_currency' => 0,
                'description'   => 'Albanian Lek - ALL (L)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'AMD',
                'exchange_rate' => 386.350403,
                'base_currency' => 0,
                'description'   => 'Armenian Dram - AMD (֏)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ANG',
                'exchange_rate' => 1.802185,
                'base_currency' => 0,
                'description'   => 'Netherlands Antillean Guilder - ANG (ƒ)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'AOA',
                'exchange_rate' => 509.000367,
                'base_currency' => 0,
                'description'   => 'Angolan Kwanza - AOA (Kz)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ARS',
                'exchange_rate' => 222.340722,
                'base_currency' => 0,
                'description'   => 'Argentine Peso - ARS ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'AUD',
                'exchange_rate' => 1.479050,
                'base_currency' => 0,
                'description'   => 'Australian Dollar - AUD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'AWG',
                'exchange_rate' => 1.802500,
                'base_currency' => 0,
                'description'   => 'Aruban Florin - AWG (ƒ)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'AZN',
                'exchange_rate' => 1.703970,
                'base_currency' => 0,
                'description'   => 'Azerbaijani Manat - AZN (₼)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BAM',
                'exchange_rate' => 1.773984,
                'base_currency' => 0,
                'description'   => 'Bosnia-Herzegovina Convertible Mark - BAM (KM)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BBD',
                'exchange_rate' => 2.019075,
                'base_currency' => 0,
                'description'   => 'Barbadian Dollar - BBD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BDT',
                'exchange_rate' => 106.485744,
                'base_currency' => 0,
                'description'   => 'Bangladeshi Taka - BDT (৳)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BGN',
                'exchange_rate' => 1.777044,
                'base_currency' => 0,
                'description'   => 'Bulgarian Lev - BGN (лв)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BHD',
                'exchange_rate' => 0.376968,
                'base_currency' => 0,
                'description'   => 'Bahraini Dinar - BHD (د.ب)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BIF',
                'exchange_rate' => 2088.000000,
                'base_currency' => 0,
                'description'   => 'Burundian Franc - BIF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BMD',
                'exchange_rate' => 1.000000,
                'base_currency' => 0,
                'description'   => 'Bermudian Dollar - BMD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BND',
                'exchange_rate' => 1.324450,
                'base_currency' => 0,
                'description'   => 'Brunei Dollar - BND ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BOB',
                'exchange_rate' => 6.908811,
                'base_currency' => 0,
                'description'   => 'Bolivian Boliviano - BOB (Bs.)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BRL',
                'exchange_rate' => 4.953104,
                'base_currency' => 0,
                'description'   => 'Brazilian Real - BRL (R$)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BSD',
                'exchange_rate' => 1.000014,
                'base_currency' => 0,
                'description'   => 'Bahamian Dollar - BSD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BTC',
                'exchange_rate' => 0.000035,
                'base_currency' => 0,
                'description'   => 'Bitcoin - BTC (₿)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BTN',
                'exchange_rate' => 81.675283,
                'base_currency' => 0,
                'description'   => 'Bhutanese Ngultrum - BTN (Nu.)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BWP',
                'exchange_rate' => 13.210097,
                'base_currency' => 0,
                'description'   => 'Botswana Pula - BWP (P)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BYR',
                'exchange_rate' => 9999.999999,
                'base_currency' => 0,
                'description'   => 'Belarusian Ruble - BYR (Br)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'BZD',
                'exchange_rate' => 2.015692,
                'base_currency' => 0,
                'description'   => 'Belize Dollar - BZD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CAD',
                'exchange_rate' => 1.347550,
                'base_currency' => 0,
                'description'   => 'Canadian Dollar - CAD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CDF',
                'exchange_rate' => 2045.726604,
                'base_currency' => 0,
                'description'   => 'Congolese Franc - CDF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CHF',
                'exchange_rate' => 0.897381,
                'base_currency' => 0,
                'description'   => 'Swiss Franc - CHF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CLF',
                'exchange_rate' => 0.028776,
                'base_currency' => 0,
                'description'   => 'Chilean Unit of Account (UF) - CLF (UF)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CLP',
                'exchange_rate' => 794.030396,
                'base_currency' => 0,
                'description'   => 'Chilean Peso - CLP ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CNY',
                'exchange_rate' => 6.910604,
                'base_currency' => 0,
                'description'   => 'Chinese Yuan - CNY (¥)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'COP',
                'exchange_rate' => 4527.050000,
                'base_currency' => 0,
                'description'   => 'Colombian Peso - COP ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CRC',
                'exchange_rate' => 542.601914,
                'base_currency' => 0,
                'description'   => 'Costa Rican Colón - CRC (₡)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CUC',
                'exchange_rate' => 1.000000,
                'base_currency' => 0,
                'description'   => 'Cuban Convertible Peso - CUC ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CUP',
                'exchange_rate' => 26.500000,
                'base_currency' => 0,
                'description'   => 'Cuban Peso - CUP ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CVE',
                'exchange_rate' => 100.350394,
                'base_currency' => 0,
                'description'   => 'Cape Verdean Escudo - CVE (Esc)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'CZK',
                'exchange_rate' => 21.224040,
                'base_currency' => 0,
                'description'   => 'Czech Koruna - CZK (Kč)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'DJF',
                'exchange_rate' => 177.720394,
                'base_currency' => 0,
                'description'   => 'Djiboutian Franc - DJF (Fdj)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'DKK',
                'exchange_rate' => 6.762204,
                'base_currency' => 0,
                'description'   => 'Danish Krone - DKK (kr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'DOP',
                'exchange_rate' => 54.420393,
                'base_currency' => 0,
                'description'   => 'Dominican Peso - DOP (RD$)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'DZD',
                'exchange_rate' => 135.223014,
                'base_currency' => 0,
                'description'   => 'Algerian Dinar - DZD (د.ج)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'EGP',
                'exchange_rate' => 30.271596,
                'base_currency' => 0,
                'description'   => 'Egyptian Pound - EGP (E£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ERN',
                'exchange_rate' => 15.000000,
                'base_currency' => 0,
                'description'   => 'Eritrean Nakfa - ERN (Nfk)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ETB',
                'exchange_rate' => 54.210392,
                'base_currency' => 0,
                'description'   => 'Ethiopian Birr - ETB (Br)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'EUR',
                'exchange_rate' => 0.892040,
                'base_currency' => 0,
                'description'   => 'Euro - EUR (€)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'FJD',
                'exchange_rate' => 2.201250,
                'base_currency' => 0,
                'description'   => 'Fijian Dollar - FJD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'FKP',
                'exchange_rate' => 0.790702,
                'base_currency' => 0,
                'description'   => 'Falkland Islands Pound - FKP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GBP',
                'exchange_rate' => 0.791202,
                'base_currency' => 0,
                'description'   => 'British Pound - GBP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GEL',
                'exchange_rate' => 2.485040,
                'base_currency' => 0,
                'description'   => 'Georgian Lari - GEL (₾)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GGP',
                'exchange_rate' => 0.790702,
                'base_currency' => 0,
                'description'   => 'Guernsey Pound - GGP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GHS',
                'exchange_rate' => 11.803858,
                'base_currency' => 0,
                'description'   => 'Ghanaian Cedi - GHS (₵)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GIP',
                'exchange_rate' => 0.790702,
                'base_currency' => 0,
                'description'   => 'Gibraltar Pound - GIP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GMD',
                'exchange_rate' => 60.203853,
                'base_currency' => 0,
                'description'   => 'Gambian Dalasi - GMD (D)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GNF',
                'exchange_rate' => 8655.000355,
                'base_currency' => 0,
                'description'   => 'Guinean Franc - GNF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GTQ',
                'exchange_rate' => 7.805024,
                'base_currency' => 0,
                'description'   => 'Guatemalan Quetzal - GTQ (Q)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'GYD',
                'exchange_rate' => 211.492063,
                'base_currency' => 0,
                'description'   => 'Guyanaese Dollar - GYD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'HKD',
                'exchange_rate' => 7.849950,
                'base_currency' => 0,
                'description'   => 'Hong Kong Dollar - HKD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'HNL',
                'exchange_rate' => 24.660389,
                'base_currency' => 0,
                'description'   => 'Honduran Lempira - HNL (L)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'HRK',
                'exchange_rate' => 6.816133,
                'base_currency' => 0,
                'description'   => 'Croatian Kuna - HRK (kn)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'HTG',
                'exchange_rate' => 150.495696,
                'base_currency' => 0,
                'description'   => 'Haitian Gourde - HTG (G)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'HUF',
                'exchange_rate' => 337.560388,
                'base_currency' => 0,
                'description'   => 'Hungarian Forint - HUF (Ft)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'IDR',
                'exchange_rate' => 9999.999999,
                'base_currency' => 0,
                'description'   => 'Indonesian Rupiah - IDR (Rp)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ILS',
                'exchange_rate' => 3.636190,
                'base_currency' => 0,
                'description'   => 'Israeli New Shekel - ILS (₪)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'INR',
                'exchange_rate' => 81.729750,
                'base_currency' => 0,
                'description'   => 'Indian Rupee - INR (₹)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'IQD',
                'exchange_rate' => 1190.000000,
                'base_currency' => 0,
                'description'   => 'Iraqi Dinar - IQD (ع.د)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'IRR',
                'exchange_rate' => 42105.000000,
                'base_currency' => 0,
                'description'   => 'Iranian Rial - IRR (﷼)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ISK',
                'exchange_rate' => 127.000000,
                'base_currency' => 0,
                'description'   => 'Icelandic Króna - ISK (kr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'JEP',
                'exchange_rate' => 0.790702,
                'base_currency' => 0,
                'description'   => 'Jersey Pound - JEP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'JMD',
                'exchange_rate' => 150.495696,
                'base_currency' => 0,
                'description'   => 'Jamaican Dollar - JMD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'JOD',
                'exchange_rate' => 0.709000,
                'base_currency' => 0,
                'description'   => 'Jordanian Dinar - JOD (د.ا)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'JPY',
                'exchange_rate' => 107.000000,
                'base_currency' => 0,
                'description'   => 'Japanese Yen - JPY (¥)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KES',
                'exchange_rate' => 106.000000,
                'base_currency' => 0,
                'description'   => 'Kenyan Shilling - KES (KSh)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KGS',
                'exchange_rate' => 84.000000,
                'base_currency' => 0,
                'description'   => 'Kyrgyzstani Som - KGS (с)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KHR',
                'exchange_rate' => 4000.000000,
                'base_currency' => 0,
                'description'   => 'Cambodian Riel - KHR (៛)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KID',
                'exchange_rate' => 1.479050,
                'base_currency' => 0,
                'description'   => 'Kiribati Dollar - KID ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KMF',
                'exchange_rate' => 417.000000,
                'base_currency' => 0,
                'description'   => 'Comorian Franc - KMF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KPW',
                'exchange_rate' => 900.000000,
                'base_currency' => 0,
                'description'   => 'North Korean Won - KPW (₩)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KRW',
                'exchange_rate' => 1200.000000,
                'base_currency' => 0,
                'description'   => 'South Korean Won - KRW (₩)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KWD',
                'exchange_rate' => 0.303000,
                'base_currency' => 0,
                'description'   => 'Kuwaiti Dinar - KWD (د.ك)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KYD',
                'exchange_rate' => 0.833000,
                'base_currency' => 0,
                'description'   => 'Cayman Islands Dollar - KYD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'KZT',
                'exchange_rate' => 420.000000,
                'base_currency' => 0,
                'description'   => 'Kazakhstani Tenge - KZT (₸)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'LAK',
                'exchange_rate' => 9000.000000,
                'base_currency' => 0,
                'description'   => 'Lao Kip - LAK (₭)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'LBP',
                'exchange_rate' => 1500.000000,
                'base_currency' => 0,
                'description'   => 'Lebanese Pound - LBP (ل.ل)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'LKR',
                'exchange_rate' => 200.000000,
                'base_currency' => 0,
                'description'   => 'Sri Lankan Rupee - LKR (Rs)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'LRD',
                'exchange_rate' => 200.000000,
                'base_currency' => 0,
                'description'   => 'Liberian Dollar - LRD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'LSL',
                'exchange_rate' => 15.000000,
                'base_currency' => 0,
                'description'   => 'Lesotho Loti - LSL (L)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'LYD',
                'exchange_rate' => 4.500000,
                'base_currency' => 0,
                'description'   => 'Libyan Dinar - LYD (ل.د)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MAD',
                'exchange_rate' => 9.000000,
                'base_currency' => 0,
                'description'   => 'Moroccan Dirham - MAD (د.م.)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MDL',
                'exchange_rate' => 17.000000,
                'base_currency' => 0,
                'description'   => 'Moldovan Leu - MDL (L)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MGA',
                'exchange_rate' => 3700.000000,
                'base_currency' => 0,
                'description'   => 'Malagasy Ariary - MGA (Ar)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MKD',
                'exchange_rate' => 50.000000,
                'base_currency' => 0,
                'description'   => 'Macedonian Denar - MKD (ден)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MMK',
                'exchange_rate' => 1500.000000,
                'base_currency' => 0,
                'description'   => 'Myanmar Kyat - MMK (K)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MNT',
                'exchange_rate' => 2400.000000,
                'base_currency' => 0,
                'description'   => 'Mongolian Tugrik - MNT (₮)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MOP',
                'exchange_rate' => 8.000000,
                'base_currency' => 0,
                'description'   => 'Macanese Pataca - MOP (P)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MRU',
                'exchange_rate' => 37.000000,
                'base_currency' => 0,
                'description'   => 'Mauritanian Ouguiya - MRU (UM)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MUR',
                'exchange_rate' => 40.000000,
                'base_currency' => 0,
                'description'   => 'Mauritian Rupee - MUR (₨)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MVR',
                'exchange_rate' => 15.000000,
                'base_currency' => 0,
                'description'   => 'Maldivian Rufiyaa - MVR (Rf)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MWK',
                'exchange_rate' => 800.000000,
                'base_currency' => 0,
                'description'   => 'Malawian Kwacha - MWK (MK)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MXN',
                'exchange_rate' => 24.000000,
                'base_currency' => 0,
                'description'   => 'Mexican Peso - MXN ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MYR',
                'exchange_rate' => 4.000000,
                'base_currency' => 0,
                'description'   => 'Malaysian Ringgit - MYR (RM)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'MZN',
                'exchange_rate' => 63.000000,
                'base_currency' => 0,
                'description'   => 'Mozambican Metical - MZN (MT)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'NAD',
                'exchange_rate' => 18.000000,
                'base_currency' => 0,
                'description'   => 'Namibian Dollar - NAD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'NGN',
                'exchange_rate' => 461.000000,
                'base_currency' => 0,
                'description'   => 'Nigerian Naira - NGN (₦)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'NIO',
                'exchange_rate' => 36.000000,
                'base_currency' => 0,
                'description'   => 'Nicaraguan Córdoba - NIO (C$)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'NOK',
                'exchange_rate' => 10.000000,
                'base_currency' => 0,
                'description'   => 'Norwegian Krone - NOK (kr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'NPR',
                'exchange_rate' => 130.000000,
                'base_currency' => 0,
                'description'   => 'Nepalese Rupee - NPR (₨)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'NZD',
                'exchange_rate' => 1.000000,
                'base_currency' => 0,
                'description'   => 'New Zealand Dollar - NZD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'OMR',
                'exchange_rate' => 0.385000,
                'base_currency' => 0,
                'description'   => 'Omani Rial - OMR (ر.ع.)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'PAB',
                'exchange_rate' => 1.000000,
                'base_currency' => 0,
                'description'   => 'Panamanian Balboa - PAB (B/.)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'PEN',
                'exchange_rate' => 3.700000,
                'base_currency' => 0,
                'description'   => 'Peruvian Sol - PEN (S/.)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'PGK',
                'exchange_rate' => 3.520000,
                'base_currency' => 0,
                'description'   => 'Papua New Guinean Kina - PGK (K)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'PHP',
                'exchange_rate' => 55.000000,
                'base_currency' => 0,
                'description'   => 'Philippine Peso - PHP (₱)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'PKR',
                'exchange_rate' => 283.000000,
                'base_currency' => 0,
                'description'   => 'Pakistani Rupee - PKR (₨)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'PLN',
                'exchange_rate' => 4.000000,
                'base_currency' => 0,
                'description'   => 'Polish Złoty - PLN (zł)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'PYG',
                'exchange_rate' => 7168.000000,
                'base_currency' => 0,
                'description'   => 'Paraguayan Guaraní - PYG (₲)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'QAR',
                'exchange_rate' => 3.640000,
                'base_currency' => 0,
                'description'   => 'Qatari Riyal - QAR (ر.ق)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'RON',
                'exchange_rate' => 4.000000,
                'base_currency' => 0,
                'description'   => 'Romanian Leu - RON (lei)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'RSD',
                'exchange_rate' => 105.000000,
                'base_currency' => 0,
                'description'   => 'Serbian Dinar - RSD (дин)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'RUB',
                'exchange_rate' => 77.000000,
                'base_currency' => 0,
                'description'   => 'Russian Ruble - RUB (₽)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'RWF',
                'exchange_rate' => 1118.000000,
                'base_currency' => 0,
                'description'   => 'Rwandan Franc - RWF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SAR',
                'exchange_rate' => 3.750000,
                'base_currency' => 0,
                'description'   => 'Saudi Riyal - SAR (ر.س)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SBD',
                'exchange_rate' => 8.000000,
                'base_currency' => 0,
                'description'   => 'Solomon Islands Dollar - SBD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SCR',
                'exchange_rate' => 13.000000,
                'base_currency' => 0,
                'description'   => 'Seychellois Rupee - SCR (₨)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SDG',
                'exchange_rate' => 598.000000,
                'base_currency' => 0,
                'description'   => 'Sudanese Pound - SDG (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SEK',
                'exchange_rate' => 10.000000,
                'base_currency' => 0,
                'description'   => 'Swedish Krona - SEK (kr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SGD',
                'exchange_rate' => 1.000000,
                'base_currency' => 0,
                'description'   => 'Singapore Dollar - SGD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SHP',
                'exchange_rate' => 0.790702,
                'base_currency' => 0,
                'description'   => 'Saint Helena Pound - SHP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SLL',
                'exchange_rate' => 10000.000000,
                'base_currency' => 0,
                'description'   => 'Sierra Leonean Leone - SLL (Le)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SOS',
                'exchange_rate' => 600.000000,
                'base_currency' => 0,
                'description'   => 'Somali Shilling - SOS (Sh)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SRD',
                'exchange_rate' => 7.000000,
                'base_currency' => 0,
                'description'   => 'Surinamese Dollar - SRD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SSP',
                'exchange_rate' => 130.000000,
                'base_currency' => 0,
                'description'   => 'South Sudanese Pound - SSP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'STN',
                'exchange_rate' => 21.000000,
                'base_currency' => 0,
                'description'   => 'São Tomé and Príncipe Dobra - STN (Db)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SYP',
                'exchange_rate' => 515.000000,
                'base_currency' => 0,
                'description'   => 'Syrian Pound - SYP (£)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SZL',
                'exchange_rate' => 15.000000,
                'base_currency' => 0,
                'description'   => 'Swazi Lilangeni - SZL (L)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'THB',
                'exchange_rate' => 30.000000,
                'base_currency' => 0,
                'description'   => 'Thai Baht - THB (฿)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TJS',
                'exchange_rate' => 11.000000,
                'base_currency' => 0,
                'description'   => 'Tajikistani Somoni - TJS (ЅМ)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TMT',
                'exchange_rate' => 3.500000,
                'base_currency' => 0,
                'description'   => 'Turkmenistani Manat - TMT (T)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TND',
                'exchange_rate' => 3.000000,
                'base_currency' => 0,
                'description'   => 'Tunisian Dinar - TND (د.ت)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TOP',
                'exchange_rate' => 2.000000,
                'base_currency' => 0,
                'description'   => 'Tongan Paʻanga - TOP (T$)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TRY',
                'exchange_rate' => 7.000000,
                'base_currency' => 0,
                'description'   => 'Turkish Lira - TRY (₺)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TTD',
                'exchange_rate' => 6.700000,
                'base_currency' => 0,
                'description'   => 'Trinidad and Tobago Dollar - TTD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TWD',
                'exchange_rate' => 30.593104,
                'base_currency' => 0,
                'description'   => 'New Taiwan Dollar - TWD (NT$)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'TZS',
                'exchange_rate' => 2355.000335,
                'base_currency' => 0,
                'description'   => 'Tanzanian Shilling - TZS (Sh)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'UAH',
                'exchange_rate' => 36.937310,
                'base_currency' => 0,
                'description'   => 'Ukrainian Hryvnia - UAH (₴)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'UGX',
                'exchange_rate' => 3719.778500,
                'base_currency' => 0,
                'description'   => 'Ugandan Shilling - UGX (Sh)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'USD',
                'exchange_rate' => 1.000000,
                'base_currency' => 1,
                'description'   => 'United States Dollar - USD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'UYU',
                'exchange_rate' => 39.093325,
                'base_currency' => 0,
                'description'   => 'Uruguayan Peso - UYU ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'UZS',
                'exchange_rate' => 9999.999999,
                'base_currency' => 0,
                'description'   => 'Uzbekistani Som - UZS (лв)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'VEF',
                'exchange_rate' => 9999.999999,
                'base_currency' => 0,
                'description'   => 'Venezuelan Bolívar - VEF (Bs)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'VES',
                'exchange_rate' => 25.026391,
                'base_currency' => 0,
                'description'   => 'Venezuelan Bolívar Soberano - VES (Bs.S)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'VND',
                'exchange_rate' => 9999.999999,
                'base_currency' => 0,
                'description'   => 'Vietnamese Đồng - VND (₫)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'VUV',
                'exchange_rate' => 118.540791,
                'base_currency' => 0,
                'description'   => 'Vanuatu Vatu - VUV (Vt)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'WST',
                'exchange_rate' => 2.712426,
                'base_currency' => 0,
                'description'   => 'Samoan Tala - WST (T)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'XAF',
                'exchange_rate' => 595.016735,
                'base_currency' => 0,
                'description'   => 'Central African CFA Franc - XAF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'XAG',
                'exchange_rate' => 0.038956,
                'base_currency' => 0,
                'description'   => 'Silver (troy ounce) - XAG (oz t)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'XAU',
                'exchange_rate' => 0.000496,
                'base_currency' => 0,
                'description'   => 'Gold (troy ounce) - XAU (oz t)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'XCD',
                'exchange_rate' => 2.702550,
                'base_currency' => 0,
                'description'   => 'East Caribbean Dollar - XCD ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'XDR',
                'exchange_rate' => 0.739504,
                'base_currency' => 0,
                'description'   => 'Special Drawing Rights - XDR (SDR)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'XOF',
                'exchange_rate' => 594.503597,
                'base_currency' => 0,
                'description'   => 'West African CFA Franc - XOF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'XPF',
                'exchange_rate' => 108.750364,
                'base_currency' => 0,
                'description'   => 'CFP Franc - XPF (Fr)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'YER',
                'exchange_rate' => 250.350363,
                'base_currency' => 0,
                'description'   => 'Yemeni Rial - YER (﷼)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ZAR',
                'exchange_rate' => 18.221455,
                'base_currency' => 0,
                'description'   => 'South African Rand - ZAR (R)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ZMW',
                'exchange_rate' => 17.997551,
                'base_currency' => 0,
                'description'   => 'Zambian Kwacha - ZMW (ZK)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ZWL',
                'exchange_rate' => 321.999592,
                'base_currency' => 0,
                'description'   => 'Zimbabwean Dollar - ZWL ($)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'ZMK',
                'exchange_rate' => 9001.203589,
                'base_currency' => 0,
                'description'   => 'Zambian Kwacha (pre-2013) - ZMK (ZK)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
            [
                'name'          => 'SLSH',
                'exchange_rate' => 8950.000000,
                'base_currency' => 0,
                'description'   => 'Somaliland Shilling - SLSH (SLSH)',
                'status'        => 1,
                'user_id'       => $this->userId,
                'business_id'   => $this->businessId,
            ],
        ]);
    }
}
